export const cities = [
  { value: "1273294", label: "Delhi" },
  { value: "1261481", label: "Mumbai" },
  { value: "1277333", label: "Bangalore" },
  { value: "1275004", label: "Kolkata" },
  { value: "1275339", label: "Chennai" },
  { value: "1264527", label: "Hyderabad" },
  { value: "1270642", label: "Pune" },
  { value: "1269843", label: "Jaipur" },
  { value: "1262180", label: "Lucknow" },
  { value: "1273874", label: "Ahmedabad" },
  { value: "1260086", label: "Surat" },
  { value: "1264728", label: "Indore" },
  { value: "1259229", label: "Nagpur" },
  { value: "1258986", label: "Patna" },
  { value: "1279233", label: "Thane" },
  { value: "1271308", label: "Bhopal" },
  { value: "1255364", label: "Ludhiana" },
  { value: "1267995", label: "Agra" },
  { value: "1269515", label: "Gurgaon" },
  { value: "1256237", label: "Kanpur" },
];
export const countryCodes = [
  { code: "+1", country: "🇺🇸 United States" },
  { code: "+44", country: "🇬🇧 United Kingdom" },
  { code: "+91", country: "🇮🇳 India" },
  { code: "+86", country: "🇨🇳 China" },
  { code: "+81", country: "🇯🇵 Japan" },
  { code: "+49", country: "🇩🇪 Germany" },
  { code: "+33", country: "🇫🇷 France" },
  { code: "+39", country: "🇮🇹 Italy" },
  { code: "+7", country: "🇷🇺 Russia" },
  { code: "+55", country: "🇧🇷 Brazil" },
  { code: "+52", country: "🇲🇽 Mexico" },
  { code: "+34", country: "🇪🇸 Spain" },
  { code: "+61", country: "🇦🇺 Australia" },
  { code: "+1", country: "🇨🇦 Canada" },
  { code: "+82", country: "🇰🇷 South Korea" },
  { code: "+31", country: "🇳🇱 Netherlands" },
  { code: "+90", country: "🇹🇷 Turkey" },
  { code: "+46", country: "🇸🇪 Sweden" },
  { code: "+41", country: "🇨🇭 Switzerland" },
  { code: "+65", country: "🇸🇬 Singapore" },
  { code: "+27", country: "🇿🇦 South Africa" },
  { code: "+54", country: "🇦🇷 Argentina" },
  { code: "+20", country: "🇪🇬 Egypt" },
  { code: "+66", country: "🇹🇭 Thailand" },
  { code: "+92", country: "🇵🇰 Pakistan" },
  { code: "+62", country: "🇮🇩 Indonesia" },
  { code: "+84", country: "🇻🇳 Vietnam" },
  { code: "+60", country: "🇲🇾 Malaysia" },
  { code: "+63", country: "🇵🇭 Philippines" },
  { code: "+64", country: "🇳🇿 New Zealand" },
  { code: "+43", country: "🇦🇹 Austria" },
  { code: "+32", country: "🇧🇪 Belgium" },
  { code: "+45", country: "🇩🇰 Denmark" },
  { code: "+358", country: "🇫🇮 Finland" },
  { code: "+30", country: "🇬🇷 Greece" },
  { code: "+353", country: "🇮🇪 Ireland" },
  { code: "+972", country: "🇮🇱 Israel" },
  { code: "+47", country: "🇳🇴 Norway" },
  { code: "+351", country: "🇵🇹 Portugal" },
  { code: "+48", country: "🇵🇱 Poland" },
  { code: "+40", country: "🇷🇴 Romania" },
  { code: "+36", country: "🇭🇺 Hungary" },
  { code: "+420", country: "🇨🇿 Czech Republic" },
  { code: "+56", country: "🇨🇱 Chile" },
  { code: "+57", country: "🇨🇴 Colombia" },
  { code: "+58", country: "🇻🇪 Venezuela" },
  { code: "+51", country: "🇵🇪 Peru" },
  { code: "+971", country: "🇦🇪 United Arab Emirates" },
  { code: "+966", country: "🇸🇦 Saudi Arabia" },
  { code: "+98", country: "🇮🇷 Iran" },
  { code: "+880", country: "🇧🇩 Bangladesh" },
  { code: "+234", country: "🇳🇬 Nigeria" },
  { code: "+254", country: "🇰🇪 Kenya" },
  { code: "+380", country: "🇺🇦 Ukraine" },
  { code: "+359", country: "🇧🇬 Bulgaria" },
  { code: "+385", country: "🇭🇷 Croatia" },
  { code: "+381", country: "🇷🇸 Serbia" },
  { code: "+352", country: "🇱🇺 Luxembourg" },
  { code: "+356", country: "🇲🇹 Malta" },
  { code: "+354", country: "🇮🇸 Iceland" },
  { code: "+371", country: "🇱🇻 Latvia" },
  { code: "+370", country: "🇱🇹 Lithuania" },
  { code: "+372", country: "🇪🇪 Estonia" },
  { code: "+373", country: "🇲🇩 Moldova" },
  { code: "+377", country: "🇲🇨 Monaco" },
  { code: "+376", country: "🇦🇩 Andorra" },
  { code: "+423", country: "🇱🇮 Liechtenstein" },
  { code: "+386", country: "🇸🇮 Slovenia" },
  { code: "+421", country: "🇸🇰 Slovakia" },
  { code: "+598", country: "🇺🇾 Uruguay" },
  { code: "+593", country: "🇪🇨 Ecuador" },
  { code: "+503", country: "🇸🇻 El Salvador" },
  { code: "+502", country: "🇬🇹 Guatemala" },
  { code: "+504", country: "🇭🇳 Honduras" },
  { code: "+506", country: "🇨🇷 Costa Rica" },
  { code: "+507", country: "🇵🇦 Panama" },
  { code: "+595", country: "🇵🇾 Paraguay" },
  { code: "+591", country: "🇧🇴 Bolivia" },
  { code: "+962", country: "🇯🇴 Jordan" },
  { code: "+961", country: "🇱🇧 Lebanon" },
  { code: "+968", country: "🇴🇲 Oman" },
  { code: "+974", country: "🇶🇦 Qatar" },
  { code: "+965", country: "🇰🇼 Kuwait" },
  { code: "+973", country: "🇧🇭 Bahrain" },
  { code: "+994", country: "🇦🇿 Azerbaijan" },
  { code: "+995", country: "🇬🇪 Georgia" },
  { code: "+993", country: "🇹🇲 Turkmenistan" },
  { code: "+998", country: "🇺🇿 Uzbekistan" },
  { code: "+996", country: "🇰🇬 Kyrgyzstan" },
  { code: "+977", country: "🇳🇵 Nepal" },
  { code: "+94", country: "🇱🇰 Sri Lanka" },
  { code: "+95", country: "🇲🇲 Myanmar" },
  { code: "+855", country: "🇰🇭 Cambodia" },
  { code: "+856", country: "🇱🇦 Laos" },
  { code: "+976", country: "🇲🇳 Mongolia" },
  { code: "+850", country: "🇰🇵 North Korea" },
  { code: "+853", country: "🇲🇴 Macau" },
  { code: "+852", country: "🇭🇰 Hong Kong" },
  { code: "+886", country: "🇹🇼 Taiwan" },
  { code: "+673", country: "🇧🇳 Brunei" },
  { code: "+670", country: "🇹🇱 East Timor" },
  { code: "+675", country: "🇵🇬 Papua New Guinea" },
  { code: "+679", country: "🇫🇯 Fiji" },
  { code: "+687", country: "🇳🇨 New Caledonia" },
  { code: "+689", country: "🇵🇫 French Polynesia" },
];
